import 'package:flutter/material.dart';

Map<String, String> stockmap = {
  'MSFT': 'Microsoft Corporation Common Stock',
  'TSLA': 'Tesla Inc. Common Stock',
  'JNJ': 'Johnson & Johnson Common Stock',
  'V': 'Visa Inc.',
  'NVDA': 'NVIDIA Corporation Common Stock',
  'XOM': 'Exxon Mobil Corporation Common Stock',
  'PG': 'Procter & Gamble Company (The) Common Stock',
  'JPM': 'JP Morgan Chase & Co. Common Stock',
  'LLY': 'Eli Lilly and Company Common Stock',
  'NVO': 'Novo Nordisk A/S Common Stock',
  'TM': 'Toyota Motor Corporation Common Stock',
  'ASML': 'ASML Holding N.V. New York Registry Shares',
  'MCD': "McDonald's Corporation Common Stock",
  'NVS': 'Novartis AG Common Stock',
  'CMCSA': 'Comcast Corporation Class A Common Stock',
  'CSCO': 'Cisco Systems Inc. Common Stock (DE)',
  'ADBE': 'Adobe Inc. Common Stock',
  'TMUS': 'T-Mobile US Inc. Common Stock',
  'CRM': 'Salesforce Inc. Common Stock',
  'QCOM': 'QUALCOMM Incorporated Common Stock',
  'INTC': 'Intel Corporation Common Stock',
  'UPS': 'United Parcel Service Inc. Common Stock',
  'WFC': 'Wells Fargo & Company Common Stock',
  'TXN': 'Texas Instruments Incorporated Common Stock',
  'LIN': 'Linde plc Ordinary Share',
  'PM': 'Philip Morris International Inc Common Stock',
  'RTX': 'Raytheon Technologies Corporation Common Stock',
  'AMD': 'Advanced Micro Devices Inc. Common Stock',
  'UNP': 'Union Pacific Corporation Common Stock',
  'RY': 'Royal Bank Of Canada Common Stock',
  'BHP':
      'BHP Group Limited American Depositary Shares (Each representing two Ordinary Shares)',
  'SNY': 'Sanofi ADS',
  'IBM': 'International Business Machines Corporation Common Stock',
  'HSBC': 'HSBC Holdings plc. Common Stock',
  'LOW': "Lowe's Companies Inc. Common Stock",
  'SPGI': 'S&P Global Inc. Common Stock',
  'UL': 'Unilever PLC Common Stock',
  'MDT': 'Medtronic plc. Ordinary Shares',
  'TD': 'Toronto Dominion Bank (The) Common Stock',
  'COP': 'ConocoPhillips Common Stock',
  'EQNR': 'Equinor ASA',
  'INTU': 'Intuit Inc. Common Stock',
  'SAP': 'SAP  SE ADS',
  'DEO': 'Diageo plc Common Stock',
  'CHTR': 'Charter Communications Inc. Class A Common Stock New',
  'JD': 'JD.com Inc. American Depositary Shares',
  'BTI': 'British American Tobacco  Industries p.l.c. Common Stock ADR',
  'SBUX': 'Starbucks Corporation Common Stock',
  'RIO': 'Rio Tinto Plc Common Stock',
  'DE': 'Deere & Company Common Stock',
  'EL': 'Estee Lauder Companies Inc. (The) Common Stock',
  'BP': 'BP p.l.c. Common Stock',
  'ENB': 'Enbridge Inc Common Stock',
  'PTR': 'PetroChina Company Limited Common Stock',
  'DUK': 'Duke Energy Corporation (Holding Company) Common Stock',
  'INFY': 'Infosys Limited American Depositary Shares',
  'GILD': 'Gilead Sciences Inc. Common Stock',
  'SO': 'Southern Company (The) Common Stock',
  'PBR': 'Petroleo Brasileiro S.A.- Petrobras Common Stock',
  'ISRG': 'Intuitive Surgical Inc. Common Stock',
  'VRTX': 'Vertex Pharmaceuticals Incorporated Common Stock',
  'BKNG': 'Booking Holdings Inc. Common Stock',
  'NOC': 'Northrop Grumman Corporation Common Stock',
  'TGT': 'Target Corporation Common Stock',
  'BX': 'Blackstone Inc. Common Stock',
  'BDX': 'Becton Dickinson and Company Common Stock',
  'IBN': 'ICICI Bank Limited Common Stock',
  'CP': 'Canadian Pacific Railway Limited Common Stock',
  'MRNA': 'Moderna Inc. Common Stock',
  'MUFG': 'Mitsubishi UFJ Financial Group Inc. Common Stock',
  'SHW': 'Sherwin-Williams Company (The) Common Stock',
  'TFC': 'Truist Financial Corporation Common Stock',
  'CSX': 'CSX Corporation Common Stock',
  'HUM': 'Humana Inc. Common Stock',
  'AMOV': 'America Movil S.A.B. de C.V. Class A American Depositary Shares',
  'FISV': 'Fiserv Inc. Common Stock',
  'EW': 'Edwards Lifesciences Corporation Common Stock',
  'VALE':
      'VALE S.A.  American Depositary Shares Each Representing one common share',
  'AMX': 'America Movil S.A.B. de C.V. American Depository Receipt Series L',
  'ABNB': 'Airbnb Inc. Class A Common Stock',
  'FDX': 'FedEx Corporation Common Stock',
  'OXY': 'Occidental Petroleum Corporation Common Stock',
  'ITW': 'Illinois Tool Works Inc. Common Stock',
  'UBS': 'UBS Group AG Registered Ordinary Shares',
  'DG': 'Dollar General Corporation Common Stock',
  'SNP': 'China Petroleum & Chemical Corporation Common Stock',
  'NSC': 'Norfolk Southern Corporation Common Stock',
  'PSA': 'Public Storage Common Stock',
  'BSX': 'Boston Scientific Corporation Common Stock',
  'ICE': 'Intercontinental Exchange Inc. Common Stock',
  'CNC': 'Centene Corporation Common Stock',
  'RELX':
      'RELX PLC PLC American Depositary Shares (Each representing One Ordinary Share)',
  'ABB': 'ABB Ltd Common Stock',
  'MCO': "Moody's Corporation Common Stock",
  'TRP': 'TC Energy Corporation Common Stock',
  'KDP': 'Keurig Dr Pepper Inc. Common Stock',
  'TRI': 'Thomson Reuters Corp Ordinary Shares',
  'ETN': 'Eaton Corporation PLC Ordinary Shares',
  'BIDU': 'Baidu Inc. ADS',
  'NGG':
      'National Grid Transco PLC National Grid PLC (NEW) American Depositary Shares',
  'MET': 'MetLife Inc. Common Stock',
  'TEAM': 'Atlassian Corporation Plc Class A Ordinary Shares',
  'GM': 'General Motors Company Common Stock',
  'SNPS': 'Synopsys Inc. Common Stock',
  'MAR': 'Marriott International Class A Common Stock',
  'EMR': 'Emerson Electric Company Common Stock',
  'KLAC': 'KLA Corporation Common Stock',
  'SLB': 'Schlumberger N.V. Common Stock',
  'VMW': 'Vmware Inc. Common stock Class A',
  'SNOW': 'Snowflake Inc. Class A Common Stock',
  'MPC': 'Marathon Petroleum Corporation Common Stock',
  'TAK':
      'Takeda Pharmaceutical Company Limited American Depositary Shares (each representing 1/2 of a share of Common Stock)',
  'KMB': 'Kimberly-Clark Corporation Common Stock',
  'UBER': 'Uber Technologies Inc. Common Stock',
  'ORLY': "O'Reilly Automotive Inc. Common Stock",
  'GIS': 'General Mills Inc. Common Stock',
  'SYY': 'Sysco Corporation Common Stock',
  'VOD': 'Vodafone Group Plc American Depositary Shares',
  'ECL': 'Ecolab Inc. Common Stock',
  'AZO': 'AutoZone Inc. Common Stock',
  'LHX': 'L3Harris Technologies Inc. Common Stock',
  'HMC': 'Honda Motor Company Ltd. Common Stock',
  'SU': 'Suncor Energy  Inc. Common Stock',
  'ROP': 'Roper Technologies Inc. Common Stock',
  'MRVL': 'Marvell Technology Inc. Common Stock',
  'NTR': 'Nutrien Ltd. Common Shares',
  'PAYX': 'Paychex Inc. Common Stock',
  'CRWD': 'CrowdStrike Holdings Inc. Class A Common Stock',
  'ITUB':
      'Itau Unibanco Banco Holding SA American Depositary Shares (Each repstg 500 Preferred shares)',
  'SHOP': 'Shopify Inc. Class A Subordinate Voting Shares',
  'SMFG':
      'Sumitomo Mitsui Financial Group Inc Unsponsored American Depositary Shares (Japan)',
  'SAN': 'Banco Santander S.A. Sponsored ADR (Spain)',
  'IQV': 'IQVIA Holdings Inc. Common Stock',
  'RSG': 'Republic Services Inc. Common Stock',
  'PSX': 'Phillips 66 Common Stock',
  'BNTX': 'BioNTech SE American Depositary Share',
  'SE':
      'Sea Limited American Depositary Shares each representing one Class A Ordinary Share',
  'WMB': 'Williams Companies Inc. (The) Common Stock',
  'CTAS': 'Cintas Corporation Common Stock',
  'SQ': 'Block Inc. Class A Common Stock',
  'KMI': 'Kinder Morgan Inc. Common Stock',
  'TEL': 'TE Connectivity Ltd. New Switzerland Registered Shares',
  'DLTR': 'Dollar Tree Inc. Common Stock',
  'BSBR':
      'Banco Santander Brasil SA American Depositary Shares each representing one unit',
  'CTVA': 'Corteva Inc. Common Stock ',
  'LI': 'Li Auto Inc. American Depositary Shares',
  'CMG': 'Chipotle Mexican Grill Inc. Common Stock',
  'WELL': 'Welltower Inc. Common Stock',
  'RACE': 'Ferrari N.V. Common Shares',
  'MSI': 'Motorola Solutions Inc. Common Stock',
  'AFL': 'AFLAC Incorporated Common Stock',
  'MELI': 'MercadoLibre Inc. Common Stock',
  'NIO':
      'NIO Inc. American depositary shares each  representing one Class A ordinary share',
  'PRU': 'Prudential Financial Inc. Common Stock',
  'ALC': 'Alcon Inc. Ordinary Shares',
  'MCHP': 'Microchip Technology Incorporated Common Stock',
  'KR': 'Kroger Company (The) Common Stock',
  'AJG': 'Arthur J. Gallagher & Co. Common Stock',
  'CTSH': 'Cognizant Technology Solutions Corporation Class A Common Stock',
  'SBAC': 'SBA Communications Corporation Class A Common Stock',
  'YUM': 'Yum! Brands Inc.',
  'MSCI': 'MSCI Inc Common Stock',
  'PUK': 'Prudential Public Limited Company Common Stock',
  'MFC': 'Manulife Financial Corporation Common Stock',
  'HLT': 'Hilton Worldwide Holdings Inc. Common Stock ',
  'BBD': 'Banco Bradesco Sa American Depositary Shares',
  'HPQ': 'HP Inc. Common Stock',
  'JCI': 'Johnson Controls International plc Ordinary Share',
  'RMD': 'ResMed Inc. Common Stock',
  'GPN': 'Global Payments Inc. Common Stock',
  'PH': 'Parker-Hannifin Corporation Common Stock',
  'DELL': 'Dell Technologies Inc. Class C Common Stock ',
  'CHT': 'Chunghwa Telecom Co. Ltd.',
  'WCN': 'Waste Connections Inc. Common Shares'
};

List<String> f = stockmap.keys.toList();

